---
- name: configurando_firewalld
  service: 
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == "RedHat"


- name: restart_httpd_redhat
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"




