- name: adicionando usuario devops
  user: 
    name: "{{item.name}}"
    state: present
    shell: "/bin/bash"
    home: "{{item.home}}"
    password: "$1$KrWUjsv6$AFJmO0eKEDiPWu2xTO29d."
  with_items: 
    - { name: devops , home: /srv/devops }
    - { name: developer , home: /srv/developer }
    - { name: marciostefani , home: /srv/marciostefani } 
