- name: criando o nosso cenario de micro servicos
  hosts: docker
  tasks:
    - name: criando o container 
      docker_container:
        name: cntr-httpd
        image: httpd
        state: started
        ports:
         - 8082:80
        volumes: 
         - /index:/usr/local/apache2/htdocs 

    - name: download do repositorio
      git: 
        repo: http://devops.dexter.com.br/marciostefani/dockerx.git
        dest: /index/
