- name: instalando o jenkins 
  hosts: automation 
  tasks:
   - name: instalacao do wget dependencia
     package: 
      name: wget
      state: present 
  
   - name: baixando repo 
     shell: "wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo"
     
   - name: instalando a chave do repo
     shell: "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"
               
   
   - name: instalando o jenkins
     package: 
       name: jenkins
       state: present
       update_cache: yes
       



    
