- name:  remover apache2 
  hosts: '{{listahosts}}'
  vars:
    - listahosts: all
  tasks: 
    - name: parando apache
      service:
        name: apache2
        state: stopped

    - name: removendo o apache2
      package:
        name: apache2
        state: absent





